### ISSUE TITLE
ctrl + assist button sometimes will make player move to a weird place

### ISSUE THREAD

**Issue by Linnnnnna** [StormyBytes/mindustry-client#26]
![8YY{@DS$HC4XA27@FCSI1L3](https://user-images.githubusercontent.com/63439268/185780201-935cb914-d95a-442c-8288-c5e8bb0fe3e4.png)

![`(8U)_S51DPT4VWS9R_B3KG](https://user-images.githubusercontent.com/63439268/185780094-9cbd36fb-0ff5-4096-a134-e5ae05c983aa.jpg)

**Comment by sbxte** [comment]
in the feature list is written that ctrl assist is cursor assist. players who use mine path or build path or are assisting other players often have their cursor pointing at 0,0. so you'll follow them to 0,0 which is the bottom left corner of the map
